// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: blocked_paths.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBlockedPathById = `-- name: DeleteBlockedPathById :exec
DELETE FROM blocked_paths WHERE id = $1
`

func (q *Queries) DeleteBlockedPathById(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBlockedPathById, id)
	return err
}

const deleteBlockedPathByPath = `-- name: DeleteBlockedPathByPath :exec
DELETE FROM blocked_paths WHERE path = $1
`

func (q *Queries) DeleteBlockedPathByPath(ctx context.Context, path string) error {
	_, err := q.db.Exec(ctx, deleteBlockedPathByPath, path)
	return err
}

const getBlockedPath = `-- name: GetBlockedPath :one
SELECT id, path, error_count, is_blocked, created_at, updated_at, error_text FROM blocked_paths
WHERE path = $1
`

func (q *Queries) GetBlockedPath(ctx context.Context, path string) (BlockedPath, error) {
	row := q.db.QueryRow(ctx, getBlockedPath, path)
	var i BlockedPath
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.ErrorCount,
		&i.IsBlocked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ErrorText,
	)
	return i, err
}

const getBlockedPaths = `-- name: GetBlockedPaths :many
SELECT id, path, error_count, is_blocked, created_at, updated_at, error_text FROM blocked_paths
`

func (q *Queries) GetBlockedPaths(ctx context.Context) ([]BlockedPath, error) {
	rows, err := q.db.Query(ctx, getBlockedPaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlockedPath
	for rows.Next() {
		var i BlockedPath
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.ErrorCount,
			&i.IsBlocked,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ErrorText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementBlockedPathErrorCount = `-- name: IncrementBlockedPathErrorCount :exec
UPDATE blocked_paths
SET
  error_count = error_count + 1,
  error_text = $2
WHERE path = $1
`

type IncrementBlockedPathErrorCountParams struct {
	Path      string
	ErrorText string
}

func (q *Queries) IncrementBlockedPathErrorCount(ctx context.Context, arg IncrementBlockedPathErrorCountParams) error {
	_, err := q.db.Exec(ctx, incrementBlockedPathErrorCount, arg.Path, arg.ErrorText)
	return err
}

const insertBlockedPath = `-- name: InsertBlockedPath :one
INSERT INTO blocked_paths (id, path, error_text) VALUES ($1, $2, $3)
RETURNING id, path, error_count, is_blocked, created_at, updated_at, error_text
`

type InsertBlockedPathParams struct {
	ID        pgtype.UUID
	Path      string
	ErrorText string
}

func (q *Queries) InsertBlockedPath(ctx context.Context, arg InsertBlockedPathParams) (BlockedPath, error) {
	row := q.db.QueryRow(ctx, insertBlockedPath, arg.ID, arg.Path, arg.ErrorText)
	var i BlockedPath
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.ErrorCount,
		&i.IsBlocked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ErrorText,
	)
	return i, err
}

const setBlockedPathAsBlocked = `-- name: SetBlockedPathAsBlocked :exec
UPDATE blocked_paths
SET is_blocked = true
WHERE path = $1
`

func (q *Queries) SetBlockedPathAsBlocked(ctx context.Context, path string) error {
	_, err := q.db.Exec(ctx, setBlockedPathAsBlocked, path)
	return err
}
