// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BlockedPath struct {
	ID         pgtype.UUID
	Path       string
	ErrorCount int32
	IsBlocked  bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Channel struct {
	ID                 pgtype.UUID
	ExtID              string
	Name               string
	Description        *string
	ImagePath          *string
	GenerateThumbnails bool
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type Chapter struct {
	ID        pgtype.UUID
	Title     string
	StartTime int32
	EndTime   int32
	VideoID   pgtype.UUID
}

type Comment struct {
	ID               string
	Text             string
	Timestamp        pgtype.Timestamptz
	LikeCount        *int32
	IsFavorited      *bool
	Author           string
	AuthorID         string
	AuthorThumbnail  *string
	AuthorIsUploader *bool
	Parent           *string
	VideoID          pgtype.UUID
}

type Video struct {
	ID             pgtype.UUID
	ExtID          *string
	Title          string
	Description    *string
	UploadDate     pgtype.Timestamptz
	Uploader       *string
	Duration       int32
	ViewCount      int64
	LikeCount      *int64
	DislikeCount   *int64
	Format         *string
	Height         *int32
	Width          *int32
	Resolution     *string
	Fps            *float32
	VideoCodec     *string
	Vbr            *float32
	AudioCodec     *string
	Abr            *float32
	CommentCount   *int32
	VideoPath      string
	ThumbnailPath  string
	InfoPath       string
	SubtitlePath   []string
	Path           string
	StoryboardPath *string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ChannelID      pgtype.UUID
	TitleFtsEn     string
}
