// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// https://docs.sqlc.dev/en/stable/howto/insert.html#using-copyfrom
	BatchInsertChapters(ctx context.Context, arg []BatchInsertChaptersParams) (int64, error)
	// -- name: InsertComment :one
	// INSERT INTO comments (
	//   id, text, timestamp, like_count, is_favorited, author, author_id, author_thumbnail, author_is_uploader, parent, video_id
	// ) VALUES (
	//   $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
	// ) RETURNING *;
	// https://docs.sqlc.dev/en/stable/howto/insert.html#using-copyfrom
	BatchInsertComments(ctx context.Context, arg []BatchInsertCommentsParams) (int64, error)
	DeleteBlockedPathById(ctx context.Context, id pgtype.UUID) error
	DeleteBlockedPathByPath(ctx context.Context, path string) error
	FtsVideosFilter(ctx context.Context, arg FtsVideosFilterParams) ([]FtsVideosFilterRow, error)
	GetAllCommentsByVideoId(ctx context.Context, videoID pgtype.UUID) ([]Comment, error)
	GetBlockedPath(ctx context.Context, path string) (BlockedPath, error)
	GetBlockedPaths(ctx context.Context) ([]BlockedPath, error)
	GetChannelByExternalId(ctx context.Context, extID string) (Channel, error)
	GetChannelById(ctx context.Context, id pgtype.UUID) (Channel, error)
	GetChannelByName(ctx context.Context, name string) (Channel, error)
	GetChannelNames(ctx context.Context) ([]string, error)
	GetChannels(ctx context.Context) ([]Channel, error)
	GetChaptersByVideoId(ctx context.Context, videoID pgtype.UUID) ([]Chapter, error)
	GetCommentById(ctx context.Context, id string) (Comment, error)
	GetCommentCountByVideoId(ctx context.Context, videoID pgtype.UUID) (int64, error)
	GetCommentRepliesByCommentId(ctx context.Context, parent *string) ([]Comment, error)
	GetCommentsFilter(ctx context.Context, arg GetCommentsFilterParams) ([]Comment, error)
	GetRootCommentsForVideoId(ctx context.Context, arg GetRootCommentsForVideoIdParams) ([]GetRootCommentsForVideoIdRow, error)
	GetVideoByExternalID(ctx context.Context, extID *string) (GetVideoByExternalIDRow, error)
	GetVideoById(ctx context.Context, id pgtype.UUID) (GetVideoByIdRow, error)
	GetVideoInfoPaths(ctx context.Context) ([]string, error)
	GetVideosCount(ctx context.Context, channelID pgtype.UUID) (int64, error)
	GetVideosFilter(ctx context.Context, arg GetVideosFilterParams) ([]GetVideosFilterRow, error)
	IncrementBlockedPathErrorCount(ctx context.Context, path string) error
	InsertBlockedPath(ctx context.Context, arg InsertBlockedPathParams) (BlockedPath, error)
	InsertChannel(ctx context.Context, arg InsertChannelParams) (Channel, error)
	InsertVideo(ctx context.Context, arg InsertVideoParams) (Video, error)
	SetBlockedPathAsBlocked(ctx context.Context, path string) error
}

var _ Querier = (*Queries)(nil)
