CREATE TABLE IF NOT EXISTS videos (
    ID varchar(250) PRIMARY KEY,
    Channel varchar(250) NOT NULL,
    Channel_ID varchar(250) NOT NULL,
    Title varchar(250) NOT NULL,
    Description text,
    Upload_Date TIMESTAMPTZ NOT NULL,
    Uploader varchar(250),
    Duration integer NOT NULL,
    View_Count bigint NOT NULL,
    Like_Count integer,
    Dislike_Count integer,
    Format varchar(250),
    Width integer,
    Height integer,
    Resolution varchar(250),
    FPS numeric,
    Video_Codec varchar(250),
    VBR numeric,
    Audio_Codec varchar(250),
    ABR numeric,
    Epoch bigint,
    Comment_Count integer NOT NULL,
    Tags text,
    Categories text,
    Video_Path text NOT NULL,
    Thumbnail_Path text NOT NULL,
    JSON_Path text,
    Subtitle_Path text,
    Created_At TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    Updated_At TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (Channel_ID) REFERENCES channels(ID)
)