// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/zibbp/avalon/internal/video"
	"html"
	"regexp"
	"strings"
)

func formatDescription(description string) string {
	// Improved link regex
	linkRegex := regexp.MustCompile(`(https?:\/\/[^\s<]+[^<.,:;"')\]\s])`)
	timestampRegex := regexp.MustCompile(`(?:(?:([01]?\d):)?([0-5]?\d))?:([0-5]?\d)`)

	// First, escape HTML special characters
	description = html.EscapeString(description)

	// Replace newlines with <br> tags
	description = strings.ReplaceAll(description, "\n", "<br>")

	// Format links
	description = linkRegex.ReplaceAllStringFunc(description, func(match string) string {
		return `<a href="` + match + `" target="_blank" class="text-sky-400">` + match + `</a>`
	})

	// Format timestamps
	description = timestampRegex.ReplaceAllStringFunc(description, func(match string) string {
		return `<span class="timestamp text-sky-300">` + match + `</span>`
	})

	return description
}

func VideoDescription(video video.Video) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"max-w-full overflow-clip\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw(formatDescription(video.Description)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
